[package]
name = "tiny-orm"
version = "0.1.1"
edition = "2021"
authors = ["Matt Delacour - mdelacour.com"]
description = "A tiny ORM for CRUD operations build on top of SQLx QueryBuilder."
license = "MIT"
repository = "https://github.com/MattDelac/tiny_orm"
documentation = "https://docs.rs/tiny-orm"
keywords = ["sqlx", "query_builder", "orm", "crud", "database"]
categories = ["database"]
readme = "README.md"
exclude = [
    "tests/*",
    "examples/*",
    ".github/*",
]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
convert_case = "<1.0"
sqlx = { version = ">=0.7, <1.0", default-features = false }

[features]
default = []
sqlite = ["sqlx/sqlite"]
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]

[dev-dependencies]
sqlx = { version = "0.8.2", features = ["runtime-tokio-native-tls", "sqlite", "chrono", "uuid", "derive"] }
tiny-orm = { path = "." }
tokio = { version = "1.41.0", features = ["rt", "macros"]}
uuid = {version = "1.11.0", features = ["v4"]}
