[package]
name = "tiny-orm-core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sqlx = { version = ">=0.7, <1.0", default-features = false }

[dev-dependencies]
tokio-test = "0.4.4"
