name: ci

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read
  actions: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
      - name: Check the documentation of lib.rs is in the README
        run: |
          cargo install cargo-rdme
          cargo rdme --check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Run doc tests
        run: cargo test --doc --workspace --features sqlite

      - name: Run lib tests on sqlite
        run: cargo test --lib --features sqlite

      - name: Run lib tests on postgres
        run: cargo test --lib --features postgres

      - name: Run lib tests on mysql
        run: cargo test --lib --features mysql

      - name: Run the integration tests on Sqlite only
        run: cargo test --tests --features sqlite


  example-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: examples
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      mysql:
        image: mysql:9
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: examples
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Run tests on sqlite
        run: cargo run --example sqlite --features sqlite

      - name: Run tests on sqlite-setoption
        run: cargo run --example sqlite-setoption --features sqlite

      - name: Run tests on Postgres
        run: cargo run --example postgres --features postgres

      - name: Run tests on Mysql
        run: cargo run --example mysql --features mysql
