name: Publish

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Publish to crates.io
        run: |
          cargo publish --features sqlite --dry-run --package tiny-orm-macros
          cargo publish --features sqlite --dry-run --package tiny-orm
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
